apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167828585
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167828585
    app.kubernetes.io/part-of: test-app-167828585
  name: java-quarkus-167828585
  namespace: yc1hkhyg-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-quarkus-167828585
status:
  loadBalancer: {}
